services:
  velma-postgres:
    image: 'postgres:15'
    container_name: 'velma-postgres'
    env_file:
      - ./backend/.env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  velma-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: velma-backend
    container_name: velma-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/local/app
    depends_on:
      - velma-postgres
    env_file:
      - ./backend/.env
    restart: on-failure

  #  velma-frontend:
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile
  #    image: velma-frontend
  #    container_name: velma-frontend
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./frontend:/app
  #      - /app/node_modules # Ensures node_modules isn't overwritten by bind mount
  #    env_file:
  #      - ./frontend/.env.local
  #    restart: on-failure

  velma-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: velma-frontend
    container_name: velma-frontend
    ports:
      - "3000:8080"  # Host:Container — expose NGINX port on 3000
    restart: on-failure

