/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as LogsIndexImport } from './routes/logs/index'
import { Route as ProductsNewImport } from './routes/products/new'
import { Route as ProductsProductIdImport } from './routes/products/$productId'
import { Route as LogsNewImport } from './routes/logs/new'
import { Route as LogsLogIdImport } from './routes/logs/$logId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const LogsIndexRoute = LogsIndexImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsNewRoute = ProductsNewImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductIdRoute = ProductsProductIdImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
} as any)

const LogsNewRoute = LogsNewImport.update({
  id: '/logs/new',
  path: '/logs/new',
  getParentRoute: () => rootRoute,
} as any)

const LogsLogIdRoute = LogsLogIdImport.update({
  id: '/logs/$logId',
  path: '/logs/$logId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/logs/$logId': {
      id: '/logs/$logId'
      path: '/logs/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogIdImport
      parentRoute: typeof rootRoute
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/logs/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewImport
      parentRoute: typeof rootRoute
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/logs/new': typeof LogsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/logs': typeof LogsIndexRoute
  '/products': typeof ProductsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/logs/new': typeof LogsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/logs': typeof LogsIndexRoute
  '/products': typeof ProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/logs/new': typeof LogsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/logs/': typeof LogsIndexRoute
  '/products/': typeof ProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/logs/$logId'
    | '/logs/new'
    | '/products/$productId'
    | '/products/new'
    | '/logs'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/logs/$logId'
    | '/logs/new'
    | '/products/$productId'
    | '/products/new'
    | '/logs'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/logs/$logId'
    | '/logs/new'
    | '/products/$productId'
    | '/products/new'
    | '/logs/'
    | '/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LogsLogIdRoute: typeof LogsLogIdRoute
  LogsNewRoute: typeof LogsNewRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  LogsIndexRoute: typeof LogsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LogsLogIdRoute: LogsLogIdRoute,
  LogsNewRoute: LogsNewRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  LogsIndexRoute: LogsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/logs/$logId",
        "/logs/new",
        "/products/$productId",
        "/products/new",
        "/logs/",
        "/products/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/logs/$logId": {
      "filePath": "logs/$logId.tsx"
    },
    "/logs/new": {
      "filePath": "logs/new.tsx"
    },
    "/products/$productId": {
      "filePath": "products/$productId.tsx"
    },
    "/products/new": {
      "filePath": "products/new.tsx"
    },
    "/logs/": {
      "filePath": "logs/index.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
