spring:
  application:
    name: Velma
  config:
    import: "classpath:env.properties"
  datasource:
    url: ${POSTGRES_LOCATION}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        security: DEBUG